### ISSUE TITLE
SVGO precision

### ISSUE THREAD

**Issue by cedriceberhardt** [BohemianCoding/svgo-compressor#1]
Hi, it doesn't look like we can define the precision. Would be cool if we could:
```
{
  [..]
  "pretty": true,
  "precision": 2,
  "indent": 2,
  [..]
}
```

Thanks.

**Comment by bomberstudios** [comment]
Precision is set for each SVGO plugin that understands the parameter (for example, `cleanupNumericValues`).

So, for example if you wanted to use that plugin, you'd do:

```json
```

**Comment by cedriceberhardt** [comment]
Perfect, thanks a lot.
