### ISSUE TITLE
What params are available for the plugins?

### ISSUE THREAD

**Issue by chrleon** [BohemianCoding/svgo-compressor#11]
More support than issue, but when I want to change svgo.json, where can I find the docs to know what params can be changed and what they do? On the github page for svgo I couldn't find anything about this either. At least not that I could understand. :)

If I wanted to change the param 'RemoveDoctype' for instance, what params can I change there?

**Comment by bomberstudios** [comment]
`removeDocType` in particular doesn't need any parameters, it just removes the doctype : )

For anything else, you just take a look at the code for the plugin you want to enable (check the list at https://github.com/svg/svgo#what-it-can-do) and look for the `exports.params` object.

For example, for [`removeEmptyText`](https://github.com/svg/svgo/blob/master/plugins/removeEmptyText.js#L9-L13), the code says:

```
exports.params = {
    text: true,
    tspan: true,
    tref: true
};
```

That means there's three parameters: `text`, `tspan` and `tref` (all of them set to `true` by default). If you want to set, say, `text` to false in this plugin, you'd open the `svgo.json` file and replace this line:

```
{ "name": "removeEmptyText" },
```

with this one:

```
{
  "name": "removeEmptyText",
  "params": {
    "text": false
  }
},
```

Hope it helps!
