### ISSUE TITLE
"xmlns" needed, for CSS background

### ISSUE THREAD

**Issue by nathansmith** [BohemianCoding/svgo-compressor#12]
I ran into an issue with `removeXMLNS`, and using SVG files as a CSS background in Chrome.

I'm not sure why, but after a lot of trial and error, I determined that the absence of…

`<svg xmlns="…">`

…caused my images to not show up.

Also of note, I'm using `background-size` in the CSS file. So, perhaps there's some perfect storm of obscurity, where if these two conditions collide, nothing shows up.

Anyway, I figured I'd point that out. Hopefully it'll save others hours of debugging! :)

**Comment by bomberstudios** [comment]
This was fixed in https://github.com/BohemianCoding/svgo-compressor/commit/1340a0a12508f9c4078337404013cac62eb6d0b2 but I somehow missed this issue! Closing : )

**Comment by nathansmith** [comment]
Awesome. No worries. :)
