### ISSUE TITLE
Exported SVG appears white, does not compare to SVGO command line

### ISSUE THREAD

**Issue by altryne** [BohemianCoding/svgo-compressor#13]
Hey guys, 
I was so happy when I heard this plugin exists, unfortunately, designers complained it didn't work. 

* Disclaimer - we use the `--disable=removeUselessStrokeAndFill` option for the command line, I followed the instructions and removed the same plugin from `svgo.json` file

I tried to reproduce the problem and this are my findings : 

![image](https://cloud.githubusercontent.com/assets/463317/23724951/92c4674c-0403-11e7-8414-de934c6a2f81.png)

`fundbox_logo_from_sketch.svg` is exported directly from sketch without svgo plugin
`fundbox_logo_from_sketch_svgo_plugin.svg` is exported using the svgo sketch plugin, and doesn't work (appears white, doesn't show the logo)
`fundbox_logo_optimized_command_line.svg` - is the first file version, optimized with the svgo command line like so : 
`svgo /Users/altryne/Downloads/fundbox_logo_optimized_command_line.svg --disable=removeUselessStrokeAndFill`

As you can see, the results are not the same, the command line SVGO exports a much smaller file, and it still works. SVGO plugin exports a badly formatted file (I didn't dive in to understand why, beyond a very basic text comparison)

EDIT : 
Attaching all three SVG files in a zip
[Archive 2.zip](https://github.com/BohemianCoding/svgo-compressor/files/829018/Archive.2.zip)

**Comment by bomberstudios** [comment]
I believe this was an error that I fixed here https://github.com/BohemianCoding/svgo-compressor/commit/1340a0a12508f9c4078337404013cac62eb6d0b2, so I'm closing this issue. Please reopen if that's not the case

**Comment by altryne** [comment]
Downloaded the new plugin 1.3.7 and exported the same file again. It's still blank. (attaching zip)
[Fundbox Logo svgo.svg.zip](https://github.com/BohemianCoding/svgo-compressor/files/900090/Fundbox.Logo.svgo.svg.zip)

**Comment by altryne** [comment]
@bomberstudios not sure how to re-open

**Comment by bomberstudios** [comment]
@altryne please make sure you've reset your `svgo.json` file (just remove it and it will be recreated the first time the plugin runs) because otherwise you'll still be using the old settings.
