### ISSUE TITLE
cleanupListOfValues doesn't work for paths

### ISSUE THREAD

**Issue by TheDutchCoder** [BohemianCoding/svgo-compressor#15]
For some reason paths are not affected by this plugin, which probably is the cause of the majority of bloat.

Would it be possible to enable this for paths as well?

Expected:
```
<path id="Fill-261" d="M6.491,19.098 C6.641,19.155
```

Actual:
```
<path id="Fill-261" d="M6.49140449,19.0979179 C6.6411236,19.1553959
```

I know this interferes with some precision, but that should be up to the user's config.

**Comment by TheDutchCoder** [comment]
Nevermind, looks like this is handled by a different plugin: `convertPathData`, thanks!

**Comment by bomberstudios** [comment]
np, SVGO plugins are sometimes confusing : )
