### ISSUE TITLE
Add file prefixing to ID's - in particular paths

### ISSUE THREAD

**Issue by randallmlough** [BohemianCoding/svgo-compressor#16]
Can we add the option to include the file name as a prefix for IDs - in particular paths? A big problem I'm running into when exporting SVGs is the auto labeling of paths as 'path-1', 'path-2' etc. which then conflicts with another SVG if it's on the same webpage.

**Comment by bomberstudios** [comment]
I added that feature in https://github.com/BohemianCoding/svgo-compressor/issues/8 : )

**Comment by randallmlough** [comment]
I see that, but how do you enabled it? 

If tried:
`"name": "cleanupIDs",
    "params": {
      "minify": false
    }`
and 
`"name": "cleanupIDs",
    "params": {
      "minify": true
    }`
and deleted the plugin call altogether, but nothing seems to change between paths not conflicting with each other.

**Comment by bomberstudios** [comment]
Make sure you're using the latest version of the plugin, and try removing the `svgo.json` file from the Plugins folder (it will be recreated on first run).

That should do the trick.

**Comment by randallmlough** [comment]
Okay - So I did have the most up-to-date version, but I still deleted the plugin and config file and re-installed it. Once I did that it worked as it should have (YAY!), which then it got me wondering why it wasn't working for me since I did have the most recent version so I ran through a couple scenarios. As mentioned earlier I deleted the cleanupIDs plugin call and re-added it later, but when I added it I didn't putting much thought in the placement of the list, so I added it after the 'cleanupListOfValues' plugin call. It appears that 'cleanupIDs' has to be first in the config file for the prefixing to work properly. 

Not sure if this is a bug or simply the way the program has to run, but I thought it was worth mentioning if something like this comes up again in the future. Thanks for your help/patience!

**Comment by randallmlough** [comment]
One final thought on this topic - the reason why I took out the plugin call / disabled it was to retain my group layer names. If I disabled minify I get my group layer names as I desire but I lose prefixing of paths. Can it be possible to add prefixing still with the minify off?

Working example - I have a laptop svg split into two parts: top-half and bottom-half. After export I have animations and styling that happens based on those groups IDS
`
#laptop-tilted-right g#top-half {
        transform: translate(211px) skew(-6deg);
    }
`
`
    #laptop-tilted-left g#top-half {
        transform: translate(0) skew(6deg);
    }
`
And the only way to have this functionality is to turn minify off but then I lose prefixing of the paths which then causes conflicts. 

Any way to have best of both worlds?

**Comment by randallmlough** [comment]
I solved my problem! 

I added the following to the config which gave me best of both worlds
`{
      "name": "cleanupIDs",
      "params": {
            "remove": false,
            "minify": true
          }
    },`
