### ISSUE TITLE
If viewbox is present set width/height = 100%

### ISSUE THREAD

**Issue by randallmlough** [BohemianCoding/svgo-compressor#17]
Rather than removing width and height if the viewbox is present, I'd like to be able to set width and height to 100%. Taking the removeDimensions.js function and tweaking it a little is all that is needed?
`
exports.fn = function(item) {
    if (
        item.isElem('svg') &&
        item.hasAttr('viewBox')
    ) {
        item.attr('width', '100%');
        item.attr('height', '100%');
    }
};
`

**Comment by mathieudutour** [comment]
You can now add your custom svgo plugin (the one you wrote looks good): https://github.com/BohemianCoding/svgo-compressor#custom-svgo-plugins
