### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by christianmagill** [BohemianCoding/svgo-compressor#19]
When I use this plugin and export to SVG the resulting files gives me the browser error shown in the title. Additionally, linking to the files via an img src attribute displays as a broken image. 

I am not sure if this is because I am using Sketch 44.1 or whether svgo-compressor is compatible with 3.8+

Thanks for any help,

**Comment by bomberstudios** [comment]
Make sure you're using the latest version of the plugin, and remove the setting file (`sgo.json` in your Plugins folder) to see if that helps.
