### ISSUE TITLE
Adding Class Names

### ISSUE THREAD

**Issue by guymeyer** [BohemianCoding/svgo-compressor#2]
Can't figure out the syntax for: 

https://github.com/svg/svgo/blob/master/plugins/addClassesToSVGElement.js

I tried emulating the syntax from the SVGO docs for this plugin, but doesn't seem to work.

P.S. this is a great plugin! should be in Sketch by default. (would also love the ability to take a set of svgs and have them wrapped into symbols, similar to the grunt iconstore plugin)

**Comment by bomberstudios** [comment]
Ah, looks like you found a bug : )

I'll investigate!

**Comment by bomberstudios** [comment]
Fixed the issue. Turns out we weren't handling SVGO plugin parameters as cleanly as we should.

Please update to the latest version of the Plugin, and add this to your `svgo.json` file, **after the `removeXMLProcInst` plugin, otherwise it will not work**:

```json
{
  "name": "addClassesToSVGElement",
  "params": {
    "classNames": ["foobar"]
  }
}
```

**Comment by guymeyer** [comment]
Thanks!

**Comment by pixi** [comment]
Is there any way to add the class to the element as such and not the outer element?
I have a special need to have a "class="fm_fill" " right after the fill color of each elemment.

**Comment by metalox** [comment]
I installed the plugin yesterday specifically to use addClassesToSVGElement and it did not work until I moved the object to immediately after the removeXMLProcInst object - so I guess this bug has not been fixed? FYI in case it helps anyone else the top of my svgo.json file now looks like this:
`{
  "comment": "This is the settings file for the SVGO Compressor Plugin. For more info, please check <https://github.com/BohemianCoding/svgo-compressor>",
  "pretty": true,
  "indent": 2,
  "floatPrecision": 3,
  "plugins": [
    {
      "name": "removeDoctype",
      "enabled": true
    },
    {
      "name": "removeXMLProcInst",
      "enabled": true
    },   
      {
      "name": "addClassesToSVGElement",
      "params": {
        "classNames": ["fm_fill"]
      },
      "enabled": true
    } ... etc...

**Comment by metalox** [comment]
as pixi comments above:
> Is there any way to add the class to the element as such and not the outer element?
> I have a special need to have a "class="fm_fill" " right after the fill color of each element.

This would be useful :) 

FYI - as far as I know  class="fm_fill" can be anywhere in the element and it should work, it does not need to be right after the fill color to work (in FileMaker)
Alternatively removing fill from all elements and  using class="fm_fill" in the svg element also works (but makes it hard to preview outside of FileMaker)

**Comment by pixi** [comment]
> FYI - as far as I know class="fm_fill" can be anywhere in the element and it should work, it does not need to be right after the fill color to work (in FileMaker)
> Alternatively removing fill from all elements and using class="fm_fill" in the svg element also works (but makes it hard to preview outside of FileMaker)

After plenty of tinkering I figured out by myself (how) to add the classes. 
And since the newer FileMaker versions have a different color on the icon picker, giving back a special fill help to identify them. So, my part looks like:

    {
      "name": "addClassesToSVGElement",
      "params": {
        "classNames": ["fm_fill"]
      }
    },
    {
      "name": "addAttributesToSVGElement",
      "params": {
        "attributes": [ "fill=\"#6B7178\"" ]
      }
    },

**Comment by metalox** [comment]
Thank you for sharing this pixi :)

**Comment by metalox** [comment]
hi pixi - which version of the plugin are you using? I am usng 1.7.0 - I can't get addAttributesToSVGElement to work - it either breaks the plugin or adds the fill="#b7b7b7" twice! (I use #b7b7b7)

**Comment by pixi** [comment]
Oops, there is a new version? I'm using 1.3.6.
And this is my full svgo.json:

{
  "comment": "This is the settings file for the SVGO Compressor Plugin. For more info, please check <https://github.com/BohemianCoding/svgo-compressor>",
  "pretty": true,
  "indent": 2,
  "plugins": [
    {
      "name": "cleanupIDs"
    },
    {
      "name": "cleanupListOfValues"
    },
    {
      "name": "cleanupNumericValues"
    },
    {
      "name": "collapseGroups"
    },
    {
      "name": "convertColors"
    },
    {
      "name": "convertStyleToAttrs"
    },
    {
      "name": "convertTransform"
    },
    {
      "name": "mergePaths"
    },
    {
      "name": "minifyStyles"
    },
    {
      "name": "removeComments"
    },
    {
      "name": "removeDesc",
      "params": {
        "removeAny": true
      }
    },
    {
      "name": "removeDoctype"
    },
    {
      "name": "removeEditorsNSData"
    },
    {
      "name": "removeEmptyAttrs"
    },
    {
      "name": "removeEmptyContainers"
    },
    {
      "name": "removeEmptyText"
    },
    {
      "name": "removeMetadata"
    },
    {
      "name": "removeNonInheritableGroupAttrs"
    },
    {
      "name": "removeTitle"
    },
    {
      "name": "removeUnknownsAndDefaults"
    },
    {
      "name": "removeUnusedNS"
    },
    {
      "name": "removeUselessDefs"
    },
    {
      "name": "removeUselessStrokeAndFill"
    },
    {
      "name": "removeXMLNS"
    },
    {
      "name": "removeXMLProcInst"
    },
    {
      "name": "addClassesToSVGElement",
      "params": {
        "classNames": ["fm_fill"]
      }
    },
    {
      "name": "addAttributesToSVGElement",
      "params": {
        "attributes": [ "fill=\"#6B7178\"" ]
      }
    },
    {
      "name": "sortAttrs"
    }
  ]
}

**Comment by pixi** [comment]
@metalox is it really true that I can't contact you directly? 
I can send you my plug too, which definitely works.

**Comment by metalox** [comment]
@pixi - I believe it is true that you can't contact me directly with GitHub :-( I will google this - I am happy for you to contact me directly, but I don't want to break any GitHub rules so I will investigate this further  - Thank you for your replies and the example code. I am using the latest version 1.7.0 ;-) with Sketch 55.2 I just started using Sketch again after a break. I develop with FileMaker 17. 
I suggest you do not update yet if everything is working for you!
Here is my svgo.json file which I set up yesterday & today -Mostly it is the original file with the addClassesToSVGElement enabled and moved to the top so it actually works. It seems like the order of 
the "plugin" objects is very important but so far I have not found the documentation for this.

svgo.json

`{
  "comment": "This is the settings file for the SVGO Compressor Plugin. For more info, please check <https://github.com/BohemianCoding/svgo-compressor>",
  "pretty": true,
  "indent": 2,
  "floatPrecision": 3,
  "plugins": [
    {
      "name": "removeDoctype",
      "enabled": true
    },
    {
      "name": "removeXMLProcInst",
      "enabled": true
    },
    {
      "name": "addClassesToSVGElement",
      "enabled": true,
      "params": {
        "classNames": [
          "fm_fill"
        ]
      }
    },
    {
      "name": "removeComments",
      "enabled": true
    },
    {
      "name": "removeMetadata",
      "enabled": true
    },
    {
      "name": "removeXMLNS",
      "enabled": false
    },
    {
      "name": "removeEditorsNSData",
      "enabled": true
    },
    {
      "name": "cleanupAttrs",
      "enabled": false
    },
    {
      "name": "inlineStyles",
      "enabled": false
    },
    {
      "name": "minifyStyles",
      "enabled": true
    },
    {
      "name": "convertStyleToAttrs",
      "enabled": true
    },
    {
      "name": "cleanupIDs",
      "enabled": true
    },
    {
      "name": "prefixIds",
      "enabled": false
    },
    {
      "name": "removeRasterImages",
      "enabled": false
    },
    {
      "name": "removeUselessDefs",
      "enabled": true
    },
    {
      "name": "cleanupNumericValues",
      "enabled": true
    },
    {
      "name": "cleanupListOfValues",
      "enabled": true
    },
    {
      "name": "convertColors",
      "enabled": true
    },
    {
      "name": "removeUnknownsAndDefaults",
      "enabled": true
    },
    {
      "name": "removeNonInheritableGroupAttrs",
      "enabled": true
    },
    {
      "name": "removeUselessStrokeAndFill",
      "enabled": true
    },
    {
      "name": "removeViewBox",
      "enabled": false
    },
    {
      "name": "cleanupEnableBackground",
      "enabled": false
    },
    {
      "name": "removeHiddenElems",
      "enabled": false
    },
    {
      "name": "removeEmptyText",
      "enabled": true
    },
    {
      "name": "convertShapeToPath",
      "enabled": false
    },
    {
      "name": "moveElemsAttrsToGroup",
      "enabled": false
    },
    {
      "name": "moveGroupAttrsToElems",
      "enabled": false
    },
    {
      "name": "collapseGroups",
      "enabled": true
    },
    {
      "name": "convertPathData",
      "enabled": false
    },
    {
      "name": "convertTransform",
      "enabled": true
    },
    {
      "name": "removeEmptyAttrs",
      "enabled": true
    },
    {
      "name": "removeEmptyContainers",
      "enabled": true
    },
    {
      "name": "mergePaths",
      "enabled": true
    },
    {
      "name": "removeUnusedNS",
      "enabled": true
    },
    {
      "name": "sortAttrs",
      "enabled": true
    },
    {
      "name": "removeTitle",
      "enabled": true
    },
    {
      "name": "removeDesc",
      "enabled": true,
      "params": {
        "removeAny": true
      }
    },
    {
      "name": "removeDimensions",
      "enabled": false
    },
    {
      "name": "removeAttrs",
      "enabled": false
    },
    {
      "name": "removeAttributesBySelector",
      "enabled": false
    },
    {
      "name": "removeElementsByAttr",
      "enabled": false
    },
    {
      "name": "removeStyleElement",
      "enabled": false
    },
    {
      "name": "removeScriptElement",
      "enabled": false
    },
          {
      "name": "addAttributesToSVGElement",
      "enabled": false,
      "params": {
        "attributes": [
          "fill=\"#b7b7b7\""
        ]
      }
    }, 
    {
      "name": "removeOffCanvasPaths",
      "enabled": false
    },
    {
      "name": "reusePaths",
      "enabled": false
    }
  ]
}`

**Comment by metalox** [comment]
@pixi - this might help: "you can contact a GitHub user by going to her/his user page (https://github.com/[USERNAME]) and on the left-hand site you should see her/his email address (if they have provided one)"

**Comment by pixi** [comment]
Yeah, that#s what I would suggest right before… ;o)
