### ISSUE TITLE
Support compression without export?

### ISSUE THREAD

**Issue by mackelito** [BohemianCoding/svgo-compressor#26]
Hey!
Just found this plugin and really like it but I use zeplin and export directly to zeplin so the svg files end up as assets in the zeplin app.

Would it be possible to compress the svgs without the export so that they will be compressed in zeplin?

**Comment by bomberstudios** [comment]
AFAIK, Zeplin does its own SVG compression: https://twitter.com/zeplin_io/status/837224316475441154 so I'm closing this issue : )
