### ISSUE TITLE
Not running cleanupNumericValues

### ISSUE THREAD

**Issue by heathflohre** [BohemianCoding/svgo-compressor#3]
In both the app and beta, the optimizations for cleanupNumericValues are not being performed. All the numbers remain at 4 places, if run as default or if the config is set using

{
      "name": "cleanupNumericValues",
      "params": {
        "floatPrecision": 2
      }
    },

**Comment by bomberstudios** [comment]
Make sure you've updated to the latest version, and check the comments in https://github.com/BohemianCoding/svgo-compressor/issues/1

I just tested it and it works as expected…

**Comment by heathflohre** [comment]
I have updated to the latest plugin and am running Sketch 39, but I still see no difference in the precision numbers. Copying the settings from comment 1 didn't help. Any ideas? Setting the parameter to 2 or 1, I still get this.

<svg xmlns="http://www.w3.org/2000/svg" width="428" height="80" viewBox="0 0 428 80" class="foobar">
  <g fill="#014F71" fill-rule="evenodd">
    <path d="M263.7945 49.069L265.7995 57.998C262.2945 60.002 256.1175 62.421 247.9385 62.421 228.4965 62.421 223.5735 46.65 223.5735 31.712 223.5735 15.607 228.3295.001 246.6875.001 261.0405.001 265.2145 8.43 266.7175 15.94L256.5355 18.444C255.2005 12.685 252.7795 8.513 246.6875 8.513 236.1725 8.513 234.8395 21.364 234.8395 31.128 234.8395 45.231 238.8445 53.325 249.5255 53.325 254.9485 53.325 259.4565 51.573 263.7945 49.069M343.1423 38.8887C343.1423 31.7117 342.1423 24.2007 335.4653 24.2007 328.5403 24.2007 327.2043 32.2957 327.2043 39.3057 327.2043 47.5677 328.8733 53.9927 335.0483 53.9927 341.6423 53.9927 343.1423 46.5657 343.1423 38.8887M316.4383 39.2217C316.4383 26.3717 322.4483 15.9397 335.7173 15.9397 349.9853 15.9397 353.9933 26.6217 353.9933 38.4707 353.9933 50.4047 348.9013 62.2547 334.7993 62.2547 320.6123 62.2547 316.4383 50.3217 316.4383 39.2217M371.4328 51.656C372.5998 52.574 374.8528 53.91 378.4398 53.91 384.7018 53.91 386.4528 46.565 386.4528 37.47 386.4528 27.373 383.8658 24.702 379.7758 24.702 376.5228 24.702 373.0178 26.705 371.4328 27.789L371.4328 51.656zM370.7638 16.774L371.0968 20.613C374.0198 18.444 378.1918 15.94 383.4478 15.94 391.2938 15.94 397.1338 21.948 397.1338 35.634 397.1338 50.321 392.8778 61.921 380.7788 61.921 377.5228 61.921 374.0198 61.086 371.3478 59.417L371.3478 79.253 360.9998 79.253 360.9998 16.774 370.7638 16.774zM417.0672 24.2843L417.0672 47.0663C417.0672 50.4043 417.4002 53.5753 421.1572 53.5753 423.0742 53.5753 424.8282 52.9083 426.8312 51.9903L428.0002 60.0013C425.3282 61.2533 421.5742 62.1713 418.1522 62.1713 409.6392 62.1713 406.5522 57.2463 406.5522 49.9873L406.5522 24.2843 400.7932 24.2843 400.7932 16.7743 406.5522 16.7743 406.5522 9.3483 417.0672 4.2573 417.0672 16.7743 427.0822 16.7743 427.0822 24.2843 417.0672 24.2843zM296.1989 15.9397C291.0249 15.9397 286.6019 18.1937 283.5149 20.6957L283.5149-.0003 272.9999 5.0897 272.9999 61.2537 283.5149 61.2537 283.5149 28.7917C285.9349 26.6217 289.1069 24.6187 292.5269 24.6187 297.0349 24.6187 298.1189 26.5377 298.1189 32.1287L298.1189 61.2537 308.5499 61.2537 308.5499 30.7937C308.5499 21.6137 306.0469 15.9397 296.1989 15.9397"/>
    <polygon points="0 1.253 46.205 1.253 46.205 9.681 28.682 9.681 28.682 61.253 18 61.253 18 9.681 0 9.681"/>
    <path d="M124.7896 20.5294L120.1156 28.0404C118.8646 26.4544 117.2796 25.5364 115.3596 25.5364 112.2726 25.5364 109.2676 27.5394 107.5146 29.3754L107.5146 61.2534 96.9996 61.2534 96.9996 16.7744 106.3466 16.7744 106.7636 21.4474C109.0176 18.7774 112.1876 15.9394 117.0286 15.9394 120.7846 15.9394 123.2876 18.3604 124.7896 20.5294M144.1576 23.6177C139.1526 23.6177 136.9806 28.5407 136.9806 34.2997L150.8346 34.2997C150.8346 27.0397 148.3316 23.6177 144.1576 23.6177L144.1576 23.6177zM136.8986 40.8077C137.0656 49.2367 140.9886 53.6587 147.3296 53.6587 151.5856 53.6587 155.5086 52.4077 159.2616 50.3217L159.8466 59.0837C156.9266 60.6687 151.7516 62.1707 146.2446 62.1707 130.5556 62.1707 126.2996 51.2397 126.2996 38.5557 126.2996 22.4487 134.2276 15.9397 144.3266 15.9397 155.7566 15.9397 160.6826 23.5347 160.6826 36.8027L160.6826 40.8077 136.8986 40.8077zM183.7096 23.6177C178.7046 23.6177 176.5326 28.5407 176.5326 34.2997L190.3866 34.2997C190.3866 27.0397 187.8836 23.6177 183.7096 23.6177L183.7096 23.6177zM176.4506 40.8077C176.6176 49.2367 180.5406 53.6587 186.8816 53.6587 191.1376 53.6587 195.0606 52.4077 198.8136 50.3217L199.3986 59.0837C196.4786 60.6687 191.3036 62.1707 185.7966 62.1707 170.1076 62.1707 165.8516 51.2397 165.8516 38.5557 165.8516 22.4487 173.7796 15.9397 183.8786 15.9397 195.3086 15.9397 200.2346 23.5347 200.2346 36.8027L200.2346 40.8077 176.4506 40.8077zM75.1989 15.9397C70.0259 15.9397 65.6029 18.1937 62.5149 20.6957L62.5149-.0003 51.9999 5.0887 51.9999 61.2537 62.5149 61.2537 62.5149 28.7917C64.9349 26.6217 68.1059 24.6187 71.5269 24.6187 76.0339 24.6187 77.1189 26.5377 77.1189 32.1287L77.1189 61.2537 87.5499 61.2537 87.5499 30.7937C87.5499 21.6137 85.0459 15.9397 75.1989 15.9397"/>
  </g>
</svg>

**Comment by bomberstudios** [comment]
Can you share a sample doc and the SVG output you're getting?

**Comment by heathflohre** [comment]
Did you download the Archive.zip file?

**Comment by bomberstudios** [comment]
Ah, sorry, somehow missed it : )

**Comment by bomberstudios** [comment]
Ok, just checked it and the Plugin is working as expected:

![screenshot 2016-08-01 12 51 38](https://cloud.githubusercontent.com/assets/3832/17291890/ca82d55c-57e6-11e6-9992-b6cc85c08dd2.png)

 You are probably expecting the wrong thing from this specific SVGO setting, it is intended to round numeric values in attributes and remove the 'px' value (see the code in https://github.com/svg/svgo/blob/master/plugins/cleanupNumericValues.js)

If you are looking for something that will remove extra decimal numbers in all your paths, you need to take a look at `convertPathData` (but keep in mind that it will mess with your path data, and the resulting paths may not always match the originals):

![screenshot 2016-08-01 12 55 50](https://cloud.githubusercontent.com/assets/3832/17291976/52879eba-57e7-11e6-924b-fd122490c01a.png)
