### ISSUE TITLE
unable to find svgo, also nothing happens when i click on the "about svgo compressor" from the plugins :\ 

### ISSUE THREAD

**Issue by ghaneshrs** [BohemianCoding/svgo-compressor#33]
im not able to find avo.json in my mac...where do i find it ?

**Comment by ghaneshrs** [comment]
nothing happens when i click on the "about svgo compressor" from the plugins, how do i open the svgo.json file to remove the fill attributes

**Comment by brianlmoon** [comment]
I am having the same issue with version 49.3.

**Comment by ghaneshrs** [comment]
any updates to this ? i have to use icomoon and remove the fill attributes bcoz this plugin isnt working :( desperately looking for a fix to this

**Comment by CITguy** [comment]
> Sketch 49.3
> SVGO Compressor v1.4.1
> Mac 10.11 (El Capitan)

You can right-click the plugin in the Preferences and select "Reveal in Finder", but the config file is at `~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/svgo.json`. 

Unfortunately, it seems that the plugin isn't working with the latest Sketch. I'm getting the same result as @ghaneshrs when I click "About SVGO Compressor" (nothing happens).  On export, I don't get a notification at the bottom of the Sketch window of the status. Nor do I get a prompt to overwrite existing files on export.

**Comment by mathieudutour** [comment]
I can't reproduce. Is there something written in the logs when you click on `About SVGO Compressor` (`~/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log`)?

**Comment by ghaneshrs** [comment]
@CITguy  did u try reinstalling sketch to see if it works ?

@mathieudutour  it still doesnt work for me :( how do i open the logs?

![image](https://user-images.githubusercontent.com/8984914/39626836-3abe21e0-4fc1-11e8-81d9-d5bb75a64bde.png)

**Comment by mathieudutour** [comment]
you would need to wrap the path in `"`: `open "~/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log"`

**Comment by ghaneshrs** [comment]
oh i did that but it says .. I tried reinstalling sketch also to see if it works but didnt work :(

![image](https://user-images.githubusercontent.com/8984914/39627731-774bf1d4-4fc4-11e8-9eaf-8fa5f3da5807.png)

**Comment by ghaneshrs** [comment]
i tried this too

![image](https://user-images.githubusercontent.com/8984914/39627812-abd1aa66-4fc4-11e8-92db-dfc588997837.png)

**Comment by ghaneshrs** [comment]
no output and when i click on "about svgo compressor" from sketch plugin menu nothing happens :(

**Comment by mathieudutour** [comment]
maybe try `open "/Users/ghaneshs/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log"`

**Comment by ghaneshrs** [comment]
still no luck :((

![image](https://user-images.githubusercontent.com/8984914/39628775-b76f7634-4fc7-11e8-9a25-6fab9f2a8298.png)

**Comment by ghaneshrs** [comment]
i even tried installing older versions of sketch to see if the plugin works but still no luck :(( any workaround at all for this ?

**Comment by IamBirgitte** [comment]
I'm getting the same issue in sketch 50.2.
Tried installs from both Sketch's site and from GitHub, the same result.
Not only am I not getting a modal when doing `About SVGO Compressor`, but the plugin doesn't seem to work at all.. When attempting to view the about or export an svg, I get a massive code dump in the logs, which seems to be the same.

My colleagues who are running the same version of sketch and SVGO Compressor, but they don't have any issues with it.

**Comment by CITguy** [comment]
### Latest Sketch + Older Plugin

> Sketch 50.2
> SVGO Compressor 1.3.7
> Mac 10.13 (High Sierra)

* I can export
* I cannot open config from the "about" modal

_attempted to open config from "about" modal_
```
ObjC method arrayWithObjects: requires 1 argument, but JavaScript passed 2 arguments
 «Plugin Output»
```

_opened export dialog (cmd+shift+E)_
```
TypeError: null is not an object (evaluating 'exports.count')
line: 30099
sourceURL: ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SVGO Compressor.sketchplugin/Contents/Sketch/plugin.js
column: 38
 «Plugin Output»
```

### Latest Sketch + Latest Plugin
> Sketch 50.2
> SVGO Compressor 1.4.1
> Mac 10.13 (High Sierra)

* I can export
* I can open config from "about" modal
* An error shows up in log upon opening the export dialog (cmd+shift+E). 
  * It doesn't seem to be breaking anything, though.

_opened export dialog (cmd+shift+E)_
```
TypeError: null is not an object (evaluating 's.length')
line: 1
sourceURL: ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SVGO Compressor.sketchplugin/Contents/Sketch/plugin.js
column: 252275
 «Plugin Output»
```

### Summary
The only change (besides updating from Sketch `49.3` to `50.2`) is that I upgraded from Mac 10.11 (El Capitan) to 10.13 (High Sierra).

**Comment by zakgreene** [comment]
Same issue — plugin doesn't work when I export SVG, `SVGO Compressor / About SVGO Compressor` appears in menu, but nothing happens when I select. Using Sketch 48. I'd like to try an older version of the plugin, but I can't find it.

**Comment by imjeen** [comment]
I am not able to find `svgo.json` file in my mac OS@10.14.3 with the  svgo@1.7.0 plugin for Sketch@52.3.

Finally I get the `svgo.json` file  after I click the`Reset SVGO Setttings` button.
