### ISSUE TITLE
Adding attributes and classes to SVG (I have a solution!)

### ISSUE THREAD

**Issue by kate-hall** [BohemianCoding/svgo-compressor#36]
In your README you note that `addAttributesToSVGElement` and `addClassesToSVGElement` don't do anything, apparently. I had a need for additional attributes, so I chased down the answer. With no modifications to your (wonderful) plugin, here's the JSON config that makes both of these plugins work as expected:

Single attribute
```
{
    "name": "addAttributesToSVGElement",
    "params": {
        "attribute": {
            "width": "100%"
        }
    }
}
```

Multiple attributes
```
{
    "name": "addAttributesToSVGElement",
    "params": {
        "attributes": [
            { "width": "100%" },
            { "height": "100%" }
        ]
    }
}
```

One class
```
{
    "name": "addClassesToSVGElement",
    "params": {
        "className": "test"
    }
}
```

Multiple classes
```
{
    "name": "addClassesToSVGElement",
    "params": {
        "classNames": [
            "test",
            "another-test"
        ]
    }
}
```

Hope this helps with updating your README, I'm sure other uses would appreciate it!

**Comment by mathieudutour** [comment]
👏 happy to accept a PR to update the readme

**Comment by kate-hall** [comment]
https://github.com/BohemianCoding/svgo-compressor/pull/37
