### ISSUE TITLE
Where can I find the default `svgo.json`. I had to modify some things for a specific project, but now want the default settings back. 

### ISSUE THREAD

**Issue by mvaneijgen** [BohemianCoding/svgo-compressor#4]
I would be nice if this was in the repo so that you can easily change things up without losing all the settings.

**Comment by bomberstudios** [comment]
Good point. You can actually get a new default `svgo.json` if you remove / rename the existing one.

For a future version, my plan is to have the Plugin try to read the file from the document's folder first, so you can store SVGO settings per project, and not have to keep tweaking settings when you change documents. Does that sound reasonable?

**Comment by mvaneijgen** [comment]
Are you sure? I have tried disabling, removing and reinstalling the plugin with no luck. My settings keep coming back.

**Comment by bomberstudios** [comment]
You need to remove the `svgo.json` file, not the plugin : )
