### ISSUE TITLE
Fix color space issue in Safari on Gaussian blur

### ISSUE THREAD

**Issue by tobamese** [BohemianCoding/svgo-compressor#40]
This is a weird issue that I run into from time to time and have just been manually declaring color-interpolation-filters="sRGB" on the feGaussianBlur to fix Safari rendering Gaussian Blurs in linear RGB by default. Rendering in linear RGB instead of sRGB causes the color to render lighter. 

It'd be awesome if we could integrate this fix into this plugin, so that design render properly in Safari. 

[gaussian-example.zip](https://github.com/BohemianCoding/svgo-compressor/files/2297637/gaussian-example.zip)

**Comment by mathieudutour** [comment]
So I have a solution using a custom SVGO plugin. Unfortunatly, it requires Sketch 52 (which is not released yet)

- https://github.com/BohemianCoding/svgo-compressor#custom-svgo-plugins
- https://gist.github.com/mathieudutour/73309f6fb7fb6e7b830e20e43ee8f850

But it's an interesting issue, I didn't know the blurs used a different color space to do their interpolation. I'll discuss it with the team, thanks
