### ISSUE TITLE
Help adding command to settings

### ISSUE THREAD

**Issue by username1290** [BohemianCoding/svgo-compressor#42]
SVGO exported files with masks are not liked by Android Studio.
An alternative to the Adobe Illustrator solution (posted a while back) is to run:
`svgo --enable=removeUnknownsAndDefaults file.svg` in Terminal to remove masks, that way SVG files can be opened in Android Studio.
Any tips to add this setting into SVGO?
EDIT: Because settings says it's enabled.

**Comment by mathieudutour** [comment]
hum masks are not unknown so I don't think it's the `removeUnknownsAndDefaults` that remove them 🤔

**Comment by username1290** [comment]
just remembered someone at SO mentioned running SVGO twice to "fix" their files. Maybe it's the same thing (first one inside Sketch, the second one in Terminal)?
🤔 detective work

**Comment by mathieudutour** [comment]
Hum interesting. By default the `multipass` setting is enabled. It's supposed to run the optimization 10 times

**Comment by mathieudutour** [comment]
anyhow, I think it'd be best to move this conversion to https://github.com/BohemianCoding/svgo-compressor/issues/14
