### ISSUE TITLE
Class with same name to a layer

### ISSUE THREAD

**Issue by stefanocerri** [BohemianCoding/svgo-compressor#46]
Hi, 
 How can I add a classname with the same name to a layer on my sketch artboard? 
Thank you, 
Cheers

**Comment by bomberstudios** [comment]
Check this plugin, which should do what you need 
https://gist.github.com/bomberstudios/848827b37bed38ca0aae5fe2bbd0843a

**Comment by bomberstudios** [comment]
See 
https://github.com/BohemianCoding/svgo-compressor#custom-svgo-plugins for instructions on how to use it
