### ISSUE TITLE
Call compress(context) function from another plugin

### ISSUE THREAD

**Issue by oodesign** [BohemianCoding/svgo-compressor#50]
Hi!

Is there any way to call the compress(context) function from another plugin? 

Tried with NSApp.delegate().runPluginCommandWithIdentifier_fromBundleAtURL_context('compress', pluginUrl, context);
But that won't work because compress is not a command...

I'm trying to do some SVG preprocessing (or postprocessing) an call SVGO compress method right after. Is it possible?

---

If I have my new plugin run on Export & ExportSlices actions too, how may I know which will trigger first? Mine, or SVGO? Would it be consistent (always same order)?

Thanks!

**Comment by mathieudutour** [comment]
> I'm trying to do some SVG preprocessing (or postprocessing) an call SVGO compress method right after

That's what svgo plugins are for: https://github.com/BohemianCoding/svgo-compressor#custom-svgo-plugins

Here is an example: https://gist.github.com/bomberstudios/848827b37bed38ca0aae5fe2bbd0843a

> Would it be consistent (always same order)?

Probably not since there are some asynchronous code in the middle
