### ISSUE TITLE
Update SVGO 1.1.1 -> 1.2.0

### ISSUE THREAD

**Issue by HYPD** [BohemianCoding/svgo-compressor#51]
👋 Could you please update the plugin to support SVGO 1.2.0? There are a few improvements in 1.2.0 that could be valuable to some of the work I'm doing.

**Comment by mathieudutour** [comment]
Some activity on SVGO :tada: 

I'm happy to accept a PR for it, should be fairly straightforward

**Comment by HYPD** [comment]
Here you go https://github.com/BohemianCoding/svgo-compressor/pull/52

**Comment by HYPD** [comment]
@mathieudutour any chance of getting this merged in this week?
