### ISSUE TITLE
Unable to use custom plugin

### ISSUE THREAD

**Issue by jrmedd** [BohemianCoding/svgo-compressor#56]
Following the README, I've just used put [this plugin](https://gist.github.com/bomberstudios/848827b37bed38ca0aae5fe2bbd0843a) from @bomberstudios into my home directory `~/SVGO-plugins/convertIdToClass.js`

Then, in my config, I'm using:
` {
            "path": "~/SVGO-plugins/convertIdToClass.js",
            "enabled": true
        }
`
But the plugin doesn't seem to work. Is there any log output I can view?

I'm on **Sketch 55.2**

Thanks!

**Comment by mathieudutour** [comment]
you need to use a relative path, `~` won't be resolved

**Comment by jrmedd** [comment]
@mathieudutour relative to the config file? In the Application Support directory?

**Comment by mathieudutour** [comment]
I think so yes (it's been a while since I haven't touch it)

I realise the docs around custom plugins could be better, feel free to send a PR if you have some ideas on how to make it clearer :)

**Comment by jrmedd** [comment]
I shall do. I symlinked the directory in the end, which is _probably_ the more upgrade-friendly approach? Also worth noting that the order of plugins in the conf is important. I'll send a PR later!
