### ISSUE TITLE
Rename plugin?

### ISSUE THREAD

**Issue by bomberstudios** [BohemianCoding/svgo-compressor#58]
While writing some technical notes about how the plugin works, I found it a bit confusing that we have different things that have a very similar name (SVGO, SVGO plugins, SVGO Compressor plugin) so I wonder if it makes sense to rename this plugin to something like "SVG Compressor".

Is anyone particularly attached to the current name?

**Comment by christianklotz** [comment]
Closing, doesn't appear to be a pressing issue at this point and potentially causes more confusion to existing users.
