### ISSUE TITLE
Multipass?

### ISSUE THREAD

**Issue by DukeOliver** [BohemianCoding/svgo-compressor#6]
In order to collapse groups fully into 1 path, as well as collapse odd transform/translates that cancel each other out, I need more than 1 pass. The current method is to export my svg's using this tool, then to use svgo via my terminal on the same file. 

Will multipass be a thing in the future for svgo-compressor?

**Comment by bomberstudios** [comment]
Could be… do you have an example (with code) of your current workflow?

**Comment by DukeOliver** [comment]
Sure! This is my biggest issue, which I can't seem to correct without multiple passes of certain plugins in svgo. My current environment is around 400 icons, housed on 1 artboard and sliced. The caveat to this method (as opposed to 400 artboards) after using svgo-compressor is that it gives me two funky transforms that cancel each other out, one in the <g> tag that I'm trying to collapse, and one in the <polygon> tag I'm trying to turn into a path:

```
<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
  <title>
    SearchBoxClearButton
  </title>
  <g fill="none" fill-rule="evenodd" transform="translate(-114 -1051)">
    <polygon fill="#B3B3B3" points="1.71 1 1 1.714 4.286 5 1 8.286 1.714 9 5 5.714 8.286 9 9 8.286 5.714 5 9 1.714 8.286 1 5 4.286" transform="translate(114 1051)"/>
  </g>
</svg>
```

I then take the icon and put it through the node-js svgo in my terminal, for another pass, and it removes the transforms as well as the grouping:

```
<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
    <title>
        SearchBoxClearButton
    </title>
    <path fill="#B3B3B3" d="M1.71 1L1 1.714 4.286 5 1 8.286 1.714 9 5 5.714 8.286 9 9 8.286 5.714 5 9 1.714 8.286 1 5 4.286z" fill-rule="evenodd"/>
</svg>

```

To my knowledge, I'm using the same plugins in both environments. It isn't a gamebreaking issue at all, but rather something that would be a nice feature, provided I'm using my plugins correctly in this instance

**Comment by bomberstudios** [comment]
Took a look at the code and I think this can be implemented easily (famous last words).

Could you please share a .sketch document with that SVG sprite (just that one, I don't need the other 399 : ) so I can run some tests?

**Comment by DukeOliver** [comment]
Funny thing, I think this might be a bug on a larger scale than this - after copying the icon to its own file, I couldn't recreate the issue. It instead looked like this upon export with svgo-compressor:

```
<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
  <title>
    SearchBoxClearButton
  </title>
  <polygon fill="#B3B3B3" fill-rule="evenodd" points="1.71 1 1 1.714 4.286 5 1 8.286 1.714 9 5 5.714 8.286 9 9 8.286 5.714 5 9 1.714 8.286 1 5 4.286"/>
</svg>
```

It's still a polygon and not a path, but my biggest issue was with the transform, which seems to have been successfully cleared! Only a select few of my icons had that problem, and I couldn't (until now) figure out how to remove the transforms from them without multiple passes of svgo. 

My solution was to take the icon+slice, which were in a folder within a folder, copy/paste it to a top level of the artboard, rename it temporarily, delete the original, then move the copy back into its original position and give it original name. 

Not really sure why this occurred. It may have to do with me copying and pasting folders between a bunch of different sketch files over the course of 6 months through different versions of sketch, which may have caused some bugs. 

I can send you the original sketch file privately if you'd still like to take a look at it, since I can't replicate the issue in a new file

**Comment by DukeOliver** [comment]
Adding to this, if I put this new copied icon in the exact same position as the old one, the bug happens again. But if I move the icon and slice 1px over, I don't get the transform issue anymore.

**Comment by bomberstudios** [comment]
WITCHCRAFT!

Feel free to send me the file to ale@sketchapp.com and I'll try to see what's going on : )

**Comment by mathieudutour** [comment]
I added an option to turn on and off multipass bu setting it as a boolean on the top level of the config
