### ISSUE TITLE
Bug: `convertShapeToPath` not working

### ISSUE THREAD

**Issue by kate-hall** [BohemianCoding/svgo-compressor#65]
All of the other config I have set up seems to be working fine, but shapes aren't converted to paths when this option is present: https://github.com/sketch-hq/svgo-compressor#convertshapetopath

My relevant settings.json:

```
{
  "comment": "This is the settings file for the SVGO Compressor Plugin. For more info, please check <https://github.com/BohemianCoding/svgo-compressor>",
  "pretty": true,
  "indent": 4,
  "plugins": [{
      "name": "convertShapeToPath"
    }]
}
```

**Comment by bomberstudios** [comment]
Sorry for the late reply. Just tested and it seems to work correctly, make sure you enable the plugin with the `enabled` property (which seems to be missing from the code you shared):

```
{
  "comment": "This is the settings file for the SVGO Compressor Plugin. For more info, please check <https://github.com/BohemianCoding/svgo-compressor>",
  "pretty": true,
  "indent": 4,
  "plugins": [
    ...
    {
      "name": "convertShapeToPath",
      "enabled": true
    },
    ...
  ]
}
```
