### ISSUE TITLE
`moveGroupAttrsToElems` appears non-functional

### ISSUE THREAD

**Issue by mbforbes** [BohemianCoding/svgo-compressor#79]
Hi there!

I'm hoping to use this to move group attrs (specially, `transform`s) to the elements inside. This is because animating groups involves mutating the `transform`, but the animation library I'm using isn't smart enough to allow relative changes to the `transform`.

Unfortunately, enabling `moveGroupAttrsToElems` in the `svgo.json` file appears to have no effect. The SVG output still has `transform` attributes on all groups, e.g.:

```svg
<g id="top-move-group" stroke="#111" stroke-width="3" transform="translate(1.988 -.254)">
    <path d="..." id="Path-2" fill="#F0F1F5"></path>
    <path d="..." id="Path-4"></path>
    <path d="..." id="Path-5"></path>
</g>
```

I am confident the edits to `svgo.json` are having _some_ effect because I've been able to, e.g., turn off `cleanupIDs` and have the IDs output.

Any help would be greatly appreciated!

**Comment by bomberstudios** [comment]
Closing, since we’ve moved to a different way to enable plugins. Please open a new issue if this is still happening with version 2 of the plugin
