### ISSUE TITLE
Way to prefix defs?

### ISSUE THREAD

**Issue by iamkevingreen** [BohemianCoding/svgo-compressor#8]
My biggest issue coming from illustrator seems to be the inline `defs` that don't seem to follow any structure other than `#a`, `#b`, `#c` so when I use the svgs inline they constantly conflict in the DOM, and thus render all the svgs poorly vs the img tag method. And since I'm all about lowering requests I prefer to inline svgs. Something like the folder/artboard name being passed in like `#mug-a`, `#globe-a`. would resolve my problem, I could also be exporting svgs wrong? Not a sketch expert.

**Comment by FritzX6** [comment]
Agreed, currently there is no suitable way to use inline svgs generated via Sketch thanks to absence of "unique id's" feature in export. This is a major dealbreaker for my team regarding usage of Sketch generated svgs.

**Comment by bomberstudios** [comment]
I have a fix for this issue working locally, and I'd like to share its behaviour with you for validation.

Basically, what it does is to create a prefix based off the asset name, and then add `a`, `b`, `c`…

So, for an asset name `icon-foo`, the refs will be named `icon-foo-a`, `icon-foo-b`, etc…

This feature would be controlled by the `minify` parameter for the svgo plugin in `svgo.json`, so you can disable it if it's not something you want.

Would something like this solve the issue for you?

**Comment by bomberstudios** [comment]
Alternatively, I could use a unique UUID for each def, but maybe that's a bit too hardcore, and not very usable…?

**Comment by bomberstudios** [comment]
Just pushed this change to the plugin, please let me know how it works for you : )
