### ISSUE TITLE
Plugin stopped working since Sketch export update (v76)

### ISSUE THREAD

**Issue by mathieudelvaux** [BohemianCoding/svgo-compressor#81]
The plugin has stopped working since update 76: SVGO doesn't run on SVG exports anymore

**Comment by kimchristiansen** [comment]
I can confirm this with sketch v 76.1

**Comment by bomberstudios** [comment]
Thanks for the report, taking a look right now!

**Comment by bomberstudios** [comment]
Ok, we’ve identified the cause for this, and will release both a Sketch and a plugin update that fixes it as soon as possible.

Thanks again for the report!
