### ISSUE TITLE
Plugin stopped working with Sketch 77

### ISSUE THREAD

**Issue by mathieudelvaux** [BohemianCoding/svgo-compressor#84]
Seems like the Sketch API introduced breaking changes in its path API as of v76.
[The same issue](https://github.com/sketch-hq/svgo-compressor/issues/81) has occurred with the latest update of Sketch 77.
We should find a way to make the latest changes introduced last time permanent with any version higher than 76

**Comment by bomberstudios** [comment]
My bad, I assumed that the fixes on Sketch’s side would be part of 77, but that’s clearly not the case. Will release an update ASAP, thanks for reporting!

**Comment by bomberstudios** [comment]
Should be fixed in v2.0.1

**Comment by mathieudelvaux** [comment]
Amazing job! 🤩
