### ISSUE TITLE
Trouble getting svgo.config.js settings to work

### ISSUE THREAD

**Issue by markstephenson** [BohemianCoding/svgo-compressor#86]
Hi, first off thank you for the plug-in and all the work lately. 

I've tried to setup a custom confirmation so I can export svg files using custom IDs but it's not working for me. Perhaps I don't have this right, here is what I've added to my svgo.cofig.js file located at the root of the plugins directory.

```js
module.exports = {
  plugins: [
    {
    name: 'preset-default',
      params: {
        overrides: {
          cleanupIDs: false,
          prefixIds: true,
        }
      }
    }
  ]
}
```

**Comment by bomberstudios** [comment]
You’re 100% right, I had a bug in the code that merges the default config with the external one, and as a result the plugin overrides were basically thrown away 🙈 

This should be fixed in v2.1.1 which I just released.
