### ISSUE TITLE
svgo.config.js does not work

### ISSUE THREAD

**Issue by damienfaivre** [BohemianCoding/svgo-compressor#92]
I have some issues with the `svgo.config.js` file. 
I just spent an insane amount of time trying to add `removeDimensions: true` but nothing seems to work. I don't even know if the config file is loaded at all.

From what I understood from your doc, SVGO doc and issue #90, I ended up with this config in `~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/svgo.config.js` :

```
module.exports = {
  path: currentFile,
  multipass: true,
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          removeViewBox: false,
          removeDimensions: true,
          removeScriptElement: true,
          removeStyleElement: true
        }
      }
    }
  ],
}
```

What's wrong with this config ?
Thanks for your help 👍

**Comment by damienfaivre** [comment]
Ok, this is kind of barbaric to me, but here is the answer I found after many, many, many attempts : 

```
module.exports = {
  multipass: false,
  datauri: 'unenc',
  js2svg: {
    indent: 2,
    pretty: true,
  },
  plugins: [
    {
      name: 'preset-default',
    },
    {
      name: 'sortAttrs',
    },
    {
      name: 'removeScriptElement',
    },
    {
      name: 'removeDimensions',
    },
  ],
};
```

It is nothing like the example in the doc, but it finally works fine.
Hope this can help someone.

**Comment by jl-stellar** [comment]
Thanks so much, finally something that works!
Since this problem still exists and is undocumented, would you mind re-opening this issue so it is easier to find?  I think this is a big issue and needs more attention.
